import Head from 'next/head'
import styles from '../styles/Layout.module.css'
import InfluencerList from '../components/InfluencerList'

export default function Home({influencers}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profiler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <InfluencerList influencers={influencers} />
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/users?_limit=6`)
  const influencers = await res.json()
  console.log(influencers);
  return {
    props: {
      influencers
    }
  }
}